"""Tests for ignore file generators (cursor, copilot, windsurf)."""

from aifence.generators.ignorefile import _merge_patterns, generate_ignore


class TestMergePatterns:
    def test_fresh_file(self):
        text, added, existed = _merge_patterns("", [".env", "*.pem"])
        assert added == 2
        assert existed == 0
        assert ".env" in text
        assert "*.pem" in text
        assert "# Generated by aifence" in text

    def test_dedup_existing(self):
        existing = ".env\n*.key\n"
        text, added, existed = _merge_patterns(existing, [".env", "*.pem", "*.key"])
        assert added == 1  # only *.pem is new
        assert existed == 2
        assert text.count(".env") == 1  # not duplicated
        assert "*.pem" in text

    def test_all_already_present(self):
        existing = ".env\n*.pem\n"
        text, added, existed = _merge_patterns(existing, [".env", "*.pem"])
        assert added == 0
        assert existed == 2
        assert text == existing  # unchanged

    def test_preserves_comments(self):
        existing = "# My custom rules\n.env\n"
        text, added, existed = _merge_patterns(existing, [".env", "*.pem"])
        assert "# My custom rules" in text
        assert ".env" in text
        assert "*.pem" in text

    def test_preserves_blank_lines(self):
        existing = ".env\n\n*.key\n"
        text, added, existed = _merge_patterns(existing, [".env", "*.key", "*.pem"])
        assert added == 1
        assert existed == 2


class TestGenerateIgnore:
    def test_creates_new_file(self, tmp_path):
        result = generate_ignore(
            workspace=tmp_path,
            filename=".testignore",
            tool_name="TestTool",
            warnings=["test warning"],
            patterns=[".env", "*.pem"],
        )
        ignore_path = tmp_path / ".testignore"
        assert ignore_path.exists()
        content = ignore_path.read_text()
        assert ".env" in content
        assert "*.pem" in content
        assert ".testignore" in result.files_modified
        assert result.warnings == ["test warning"]

    def test_merges_existing_file(self, tmp_path):
        ignore_path = tmp_path / ".testignore"
        ignore_path.write_text("*.log\n.env\n")

        result = generate_ignore(
            workspace=tmp_path,
            filename=".testignore",
            tool_name="TestTool",
            warnings=[],
            patterns=[".env", "*.pem"],
        )
        content = ignore_path.read_text()
        assert "*.log" in content  # preserved
        assert content.count(".env") == 1  # deduped
        assert "*.pem" in content  # added
        assert "1 patterns added" in result.actions[0]

    def test_all_present_no_write(self, tmp_path):
        ignore_path = tmp_path / ".testignore"
        ignore_path.write_text(".env\n*.pem\n")

        result = generate_ignore(
            workspace=tmp_path,
            filename=".testignore",
            tool_name="TestTool",
            warnings=[],
            patterns=[".env", "*.pem"],
        )
        assert "already present" in result.actions[0]
        assert len(result.files_modified) == 0

    def test_dry_run(self, tmp_path):
        result = generate_ignore(
            workspace=tmp_path,
            filename=".testignore",
            tool_name="TestTool",
            warnings=[],
            patterns=[".env"],
            dry_run=True,
        )
        assert not (tmp_path / ".testignore").exists()
        assert "would be added" in result.actions[0]

    def test_idempotent(self, tmp_path):
        generate_ignore(tmp_path, ".testignore", "T", [], [".env", "*.pem"])
        first = (tmp_path / ".testignore").read_text()

        generate_ignore(tmp_path, ".testignore", "T", [], [".env", "*.pem"])
        second = (tmp_path / ".testignore").read_text()

        assert first == second

    def test_permission_error_handled(self, tmp_path):
        """Read-only ignore file produces error, not crash."""
        ignore_path = tmp_path / ".testignore"
        ignore_path.write_text("")
        ignore_path.chmod(0o444)

        result = generate_ignore(
            workspace=tmp_path,
            filename=".testignore",
            tool_name="TestTool",
            warnings=[],
            patterns=[".env", "*.pem"],
        )
        assert len(result.errors) == 1
        assert "Permission denied" in result.errors[0]
        assert len(result.files_modified) == 0
