"""Generate ignore files for tools that use gitignore-style ignore files."""

from pathlib import Path

from aifence.generators import GeneratorResult
from aifence.patterns import PATTERNS

# Header written to generated ignore files.
_HEADER = "# Generated by aiguard — protect sensitive files from AI tools\n"


def _merge_patterns(existing_text: str, patterns: list[str]) -> tuple[str, int, int]:
    """Merge patterns into existing ignore file content.

    Returns (merged_text, added_count, existing_count).
    """
    existing_lines = {
        line.strip()
        for line in existing_text.splitlines()
        if line.strip() and not line.startswith("#")
    }
    added = [p for p in patterns if p not in existing_lines]
    existing_count = len(existing_lines & set(patterns))

    if not added:
        return existing_text, 0, existing_count

    text = existing_text.rstrip("\n")
    if text:
        text += "\n\n"
    text += _HEADER
    text += "\n".join(added) + "\n"
    return text, len(added), existing_count


def generate_ignore(
    workspace: Path,
    filename: str,
    tool_name: str,
    warnings: list[str],
    patterns: list[str] | None = None,
    dry_run: bool = False,
) -> GeneratorResult:
    """Generate or merge an ignore file."""
    patterns = patterns or PATTERNS
    result = GeneratorResult(tool_name=tool_name)
    result.warnings.extend(warnings)
    ignore_path = workspace / filename

    if dry_run:
        result.actions.append(f"{filename} — {len(patterns)} patterns would be added")
        return result

    existing = ignore_path.read_text() if ignore_path.exists() else ""
    merged, added, existed = _merge_patterns(existing, patterns)

    if added == 0:
        result.actions.append(f"{filename} — all patterns already present")
    else:
        ignore_path.write_text(merged)
        result.actions.append(f"{filename} — {added} patterns added ({existed} already existed)")
        result.files_modified.append(filename)

    return result
